services:
  angular:
    container_name: angular

    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ngi
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - deno

  deno:
    container_name: deno
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./backend:/app  # Mount source code to container
    networks:
      - app-network
    depends_on:
      - postgresql
      - garnet

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

  db-migration:
    container_name: db-migration
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./backend/.env
    depends_on:
      - deno
      - postgresql
    command: deno task push-migration
    volumes:
      - ./backend:/app

  garnet:
    container_name: garnet
    restart: always
    build:
      context: .
      dockerfile: garnet/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ~/apps/garnet:/data
    networks:
      - app-network

  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: ollama/Dockerfile
    ports: 
      - "11434:11434"
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge