services:
  app:
    container_name: app
    build: 
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount source code to container
    networks:
      - app-network
    command: ["deno", "run", "-A", "--watch", "main.ts"]

  postgres:
    container_name: postgresql
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

  garnet:
    container_name: garnet
    restart: always
    build:
      context: .
      dockerfile: garnet/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge